

//-------------------------------------------------------------------------------------------------
using System.Data;

var myInst = new MyClass();


Console.WriteLine(myInst.age);
// Console.WriteLine(myInst.Age); // Compile error... set only!
Console.WriteLine(myInst.name);
Console.WriteLine(myInst.Name);

myInst.Name = "D0n4ld Duçk";
myInst.Age  = 35;
Console.WriteLine(myInst.age);
Console.WriteLine(myInst.name);

myInst.Age  = 133;
Console.WriteLine(myInst.age);
Console.WriteLine(myInst.State);

myInst.Sex = "male";
Console.WriteLine(myInst.Sex);

//-------------------------------------------------------------------------------------------------
class MyClass {
    
    public MyClass() {
        name = "D4gobert Duçk"; // not nullable... must be set "Beim beenden des Konstruktors" :D
        age  = 100;             // source: chatgpt
        Sex  = "unknown";
    }

    public string name; // that's a "field". In C++ a public "member" or "member variable"
    public int    age;
    public string Name {
        get { Console.WriteLine("Who reads the name?"); return name;  }
        set { name = value; Console.WriteLine("Name changed!"); }
    }

    public int Age {
        set { age = value > 100 ? value : 99; }
    }

    public string State // Expression bodied property
       => (age > 70 ? "old" : "young"); 

    public string Sex { // automated generated, not nullable, property. No need to create extra member..
        get;set;
    }

    /* 
       Don't forget:
    
       "Visibility":
         {
            set { .. }
            private get {... }
         }

       "Init" for autogenerated
        { get; init; } = 42;
    */
}